<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">  
    <title>Document</title>
</head>
<body>
    <h1 class="container"><i class="bi bi-pencil-square"></i> Edit tache </h1>
<form method="POST" action="<?=$_SERVER['PHP_SELF']?>" class="container mt-5">
      
<div class="mb-3 ">
    <input type="hidden" name ="id" value="<?=$todo['id']?>">
      <input type="text" value="<?php if(isset($todo['id'])){$todo['id'];}?>"class="form-control" id="prenom" name="title" required placeholder="title tache" aria-label="title">
        </div>
        <div class="mb-3">
      <input type="date" class="form-control" id="date" name="date" required placeholder="choisir date">
      </div>

      <div class="mb-3">
  <label for="description" class="form-label" >Description</label>
  <input type="text" class="form-control" name="description" id="date" required value="<?=$todo['description']?>" >
  </div>


  <div class="mb-3">
<select class="form-select" name="completed" aria-label="Default select example">
  <option selected>completed or not!</option>
  <option value="0">0</option>
  <option value="1">1</option>
</select>
</div>


<div class="mb-3">
  <button type="button" class="btn btn-secondary" >Close</button>
  <button type="submit" class="btn btn-primary"
    data-bs-dismiss="modal">Submit</button>
</div>

</form>
</body>
</html>